Version: '${project.version}'

Config:
  Update-Notify: true

Database:
  URL: "jdbc:sqlite:DiscordUtils.sqlite"
  User:
  Password:

Bot:
  Token: ""
  Status: "ONLINE"  # ONLINE, IDLE, DO_NOT_DISTURB, OFFLINE
  Activity:
    Type: "PLAYING"
    Name: "Minecraft"

Modules:
  Profile: true
  BedWars: false

