name: DiscordStats
version: '${project.version}'
main: me.rrs.discordstats.DiscordStats
api-version: '1.13'
authors: [ RRS ]
description: Get minecraft stats in discord
website: https://discord.gg/fV4P2yMSgR

softdepend:
  - DiscordSRV
depend:
  - PlaceholderAPI
commands:
  addpapi:
    description: Set title & placeholder
    aliases: addpapi
    permission: centralbot.admin
    usage: /setpapi <title> <placeholder>

  removepapi:
    description: Remove title & placeholder
    aliases: deletepapi
    permission: centralbot.admin
    usage: /removepapi <title>

  editpapi:
    description: edit title & placeholder
    permission: centralbot.admin
    usage: /editpapi title|papi <title> <placeholder>